=begin comment

Petstore

This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 2;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('OnlinePetstore::Object::Order');

# uncomment below and update the test
#my $instance = OnlinePetstore::Object::Order->new();
#
#isa_ok($instance, 'OnlinePetstore::Object::Order');

